### ISSUE TITLE
support for displaying which pattern matched

### ISSUE THREAD

**Issue by arekm** [bridgeythegeek/grepcidr#1]
Hello.

Please add option to show which pattern matched.

Example usage case, firewall with tons of networks listed and we have one ip that we want to figure out which network matches that ip.

Like:
1.0.0.0/24
2.0.0.0/24
3.0.0.0/24

and ip 1.2.3.4

result: 1.0.0.0/24

**Comment by bridgeythegeek** [comment]
Hi @arekm. Of course, `1.2.3.4` would not match `1.0.0.0/24` 😄 but I understand what you mean. I have added the option `-p` to support showing the pattern that matched (bdd2a27). Let me know if this is what you mean.

**Comment by arekm** [comment]
Right. Meant something like 1.1.1.5 :D

Works nicely, thanks.

ps. IPv6 support would be nice and also accepting IPs in cmdline, so no need for files at all and something like
iptables -L -n -v  | awk ' { print $8 } ' | python3 grepcidr.py -f - -E 1.1.1.5 -E 1.1.3.5 -E ...
would work.

**Comment by arekm** [comment]
Something like:

https://github.com/arekm/grepcidr/commit/e6733257181830c686c0d7c27344f118877f9e6e

````
$ cat test-file
1.2.3.7
$ cat test-file-other
fe80::5:5:5:5


$ echo -ne "1.2.3.0/24\nfe80::/64\n" | python3 -u grepcidr.py  -f - -e 5.5.0.0/16 -E 1.2.3.5 -E "blah 1.2.3.7 otherblah" -E "fe80::1:2:3:4" -o -p test-file test-file-other -E 5.5.1.2
test-file;1.2.3.0/24;1.2.3.7
test-file-other;fe80::/64;fe80::5:5:5:5
<arg>;1.2.3.0/24;1.2.3.5
<arg>;1.2.3.0/24;1.2.3.7
<arg>;fe80::/64;fe80::1:2:3:4
<arg>;5.5.0.0/16;5.5.1.2


$ echo -ne "1.2.3.0/24\nfe80::/64\n" | python3 -u grepcidr.py  -f - -e 5.5.0.0/16 -E 1.2.3.5 -E "blah 1.2.3.7 otherblah" -E "fe80::1:2:3:4" -p test-file test-file-other -E 5.5.1.2 --no-file -o
1.2.3.0/24;1.2.3.7
fe80::/64;fe80::5:5:5:5
1.2.3.0/24;1.2.3.5
1.2.3.0/24;1.2.3.7
fe80::/64;fe80::1:2:3:4
5.5.0.0/16;5.5.1.2

$ echo -ne "1.2.3.0/24\nfe80::/64\n" | python3 -u grepcidr.py  -f - -e 5.5.0.0/16 -E 1.2.3.5 -E "blah 1.2.3.7 otherblah" -E "fe80::1:2:3:4" -p test-file test-file-other
test-file;1.2.3.0/24;1.2.3.7
test-file-other;fe80::/64;fe80::5:5:5:5
<arg>;1.2.3.0/24;1.2.3.5
<arg>;1.2.3.0/24;blah 1.2.3.7 otherblah
<arg>;fe80::/64;fe80::1:2:3:4
````
